main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.11"
author: mictali
description: A Simple Ships plugin
commands:
  cleanup:
    description: Remove all ship components parts
    usage: "/simpleshipsplugin cleanup"
  helm:
    description: Give player a helm
    usage: "/simpleshipsplugin helm"
  pad:
    description: Give player an entity pad
    usage: "/simpleshipsplugin pad"
  seat:
    description: Give player a passenger seat
    usage: "/simpleshipsplugin seat"
  perch:
    description: Give player a parrot perch
    usage: "/simpleshipsplugin perch"
  flush:
    description: Flush all ships and components
    usage: "/simpleshipsplugin flush"
    


    
